-- MySQL Script generated by MySQL Workbench
-- Sun Jul 13 14:31:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema oboe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oboe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oboe` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `oboe` ;

-- -----------------------------------------------------
-- Table `oboe`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`users` (
  `user_id` BINARY(16) NOT NULL,
  `account_type` ENUM('FREE', 'PREMIUM') NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `auth_provider` ENUM('EMAIL', 'GOOGLE', 'FACEBOOK') NOT NULL,
  `create_at` DATETIME(6) NOT NULL,
  `day_of_birth` DATE NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `pass_word` VARCHAR(255) NULL DEFAULT NULL,
  `provider_id` VARCHAR(255) NULL DEFAULT NULL,
  `role` ENUM('ROLE_ADMIN', 'ROLE_USER') NOT NULL,
  `status` ENUM('ACTION', 'BAN') NOT NULL,
  `update_at` DATETIME(6) NOT NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `verified` BIT(1) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `UK7bkemrnhoko16ulsq5ut5lmee` (`user_name` ASC, `auth_provider` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`blogs` (
  `blog_id` BINARY(16) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`blog_id`),
  INDEX `FKpg4damav6db6a6fh5peylcni5` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKpg4damav6db6a6fh5peylcni5`
    FOREIGN KEY (`user_id`)
    REFERENCES `oboe`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`comments` (
  `comment_id` BINARY(16) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `reference_id` BINARY(16) NOT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `parent_comment_id` BINARY(16) NULL DEFAULT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `FK7h839m3lkvhbyv3bcdv7sm4fj` (`parent_comment_id` ASC) VISIBLE,
  INDEX `FK8omq0tc18jd43bu5tjh6jvraq` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK7h839m3lkvhbyv3bcdv7sm4fj`
    FOREIGN KEY (`parent_comment_id`)
    REFERENCES `oboe`.`comments` (`comment_id`),
  CONSTRAINT `FK8omq0tc18jd43bu5tjh6jvraq`
    FOREIGN KEY (`user_id`)
    REFERENCES `oboe`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`kanji`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`kanji` (
  `kanji_id` BINARY(16) NOT NULL,
  `character_name` VARCHAR(255) NOT NULL,
  `meaning` VARCHAR(255) NULL DEFAULT NULL,
  `strokes` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`kanji_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`vocabulary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`vocabulary` (
  `vocalb_id` BINARY(16) NOT NULL,
  `meanning` VARCHAR(255) NULL DEFAULT NULL,
  `script_type` VARCHAR(255) NULL DEFAULT NULL,
  `word_type` VARCHAR(255) NULL DEFAULT NULL,
  `words` VARCHAR(255) NULL DEFAULT NULL,
  `kanji_id` BINARY(16) NULL DEFAULT NULL,
  PRIMARY KEY (`vocalb_id`),
  INDEX `FKgimkdwkdo6l2f25smnebwqhsb` (`kanji_id` ASC) VISIBLE,
  CONSTRAINT `FKgimkdwkdo6l2f25smnebwqhsb`
    FOREIGN KEY (`kanji_id`)
    REFERENCES `oboe`.`kanji` (`kanji_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`flash_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`flash_cards` (
  `card_id` BINARY(16) NOT NULL,
  `created` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `term` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`card_id`),
  INDEX `FKs9rea8h9g6x1m11nwx3v9ufq0` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKs9rea8h9g6x1m11nwx3v9ufq0`
    FOREIGN KEY (`user_id`)
    REFERENCES `oboe`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`gramma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`gramma` (
  `grammaid` BINARY(16) NOT NULL,
  `example` VARCHAR(255) NULL DEFAULT NULL,
  `explanation` VARCHAR(255) NULL DEFAULT NULL,
  `grammar_type` VARCHAR(255) NULL DEFAULT NULL,
  `structure` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`grammaid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`favorites` (
  `favoritesid` BINARY(16) NOT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `favories_at` DATE NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `card_id` BINARY(16) NULL DEFAULT NULL,
  `grammaid` BINARY(16) NULL DEFAULT NULL,
  `kanji_id` BINARY(16) NULL DEFAULT NULL,
  `user_id` BINARY(16) NULL DEFAULT NULL,
  `vocalb_id` BINARY(16) NULL DEFAULT NULL,
  PRIMARY KEY (`favoritesid`),
  INDEX `FKgrdvdl8t0h06uuvabfyv5elvb` (`card_id` ASC) VISIBLE,
  INDEX `FKogkg65pcnpfjqhjewbu10eiy6` (`grammaid` ASC) VISIBLE,
  INDEX `FKjf4l60onts2x5ywme97ilb9kq` (`kanji_id` ASC) VISIBLE,
  INDEX `FKk7du8b8ewipawnnpg76d55fus` (`user_id` ASC) VISIBLE,
  INDEX `FK7rpqavwm55yk44ke38kedeip6` (`vocalb_id` ASC) VISIBLE,
  CONSTRAINT `FK7rpqavwm55yk44ke38kedeip6`
    FOREIGN KEY (`vocalb_id`)
    REFERENCES `oboe`.`vocabulary` (`vocalb_id`),
  CONSTRAINT `FKgrdvdl8t0h06uuvabfyv5elvb`
    FOREIGN KEY (`card_id`)
    REFERENCES `oboe`.`flash_cards` (`card_id`),
  CONSTRAINT `FKjf4l60onts2x5ywme97ilb9kq`
    FOREIGN KEY (`kanji_id`)
    REFERENCES `oboe`.`kanji` (`kanji_id`),
  CONSTRAINT `FKk7du8b8ewipawnnpg76d55fus`
    FOREIGN KEY (`user_id`)
    REFERENCES `oboe`.`users` (`user_id`),
  CONSTRAINT `FKogkg65pcnpfjqhjewbu10eiy6`
    FOREIGN KEY (`grammaid`)
    REFERENCES `oboe`.`gramma` (`grammaid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`message` (
  `messageid` BINARY(16) NOT NULL,
  `sent_at` DATETIME(6) NULL DEFAULT NULL,
  `sent_message` VARCHAR(255) NULL DEFAULT NULL,
  `receiverid` BINARY(16) NULL DEFAULT NULL,
  `senderid` BINARY(16) NULL DEFAULT NULL,
  PRIMARY KEY (`messageid`),
  INDEX `FKbn3kml0f86u2jp1of74h5rp6r` (`receiverid` ASC) VISIBLE,
  INDEX `FKmbmfoyayyix0xheh6opry914n` (`senderid` ASC) VISIBLE,
  CONSTRAINT `FKbn3kml0f86u2jp1of74h5rp6r`
    FOREIGN KEY (`receiverid`)
    REFERENCES `oboe`.`users` (`user_id`),
  CONSTRAINT `FKmbmfoyayyix0xheh6opry914n`
    FOREIGN KEY (`senderid`)
    REFERENCES `oboe`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`notifications` (
  `notifi_id` BINARY(16) NOT NULL,
  `is_read` BIT(1) NOT NULL,
  `text_notification` VARCHAR(255) NULL DEFAULT NULL,
  `update_at` DATETIME(6) NULL DEFAULT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`notifi_id`),
  INDEX `FK9y21adhxn0ayjhfocscqox7bh` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK9y21adhxn0ayjhfocscqox7bh`
    FOREIGN KEY (`user_id`)
    REFERENCES `oboe`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`payment` (
  `paymentid` BINARY(16) NOT NULL,
  `amount` VARCHAR(255) NULL DEFAULT NULL,
  `payment_date` DATE NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`paymentid`),
  UNIQUE INDEX `UK_ctvskou1xh26obtbvta4d2o4l` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKmi2669nkjesvp7cd257fptl6f`
    FOREIGN KEY (`user_id`)
    REFERENCES `oboe`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`quizzes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`quizzes` (
  `quizzesid` BINARY(16) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`quizzesid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`questions` (
  `questionid` BINARY(16) NOT NULL,
  `correct_answer` VARCHAR(255) NULL DEFAULT NULL,
  `options` VARCHAR(255) NULL DEFAULT NULL,
  `question_name` VARCHAR(255) NULL DEFAULT NULL,
  `quizzesid` BINARY(16) NULL DEFAULT NULL,
  PRIMARY KEY (`questionid`),
  INDEX `FKa0wu70lh8ifwjxfewig76o21i` (`quizzesid` ASC) VISIBLE,
  CONSTRAINT `FKa0wu70lh8ifwjxfewig76o21i`
    FOREIGN KEY (`quizzesid`)
    REFERENCES `oboe`.`quizzes` (`quizzesid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`quiz_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`quiz_results` (
  `resultid` BINARY(16) NOT NULL,
  `score` DOUBLE NOT NULL,
  `taken_at` DATETIME(6) NULL DEFAULT NULL,
  `quizzesid` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  PRIMARY KEY (`resultid`),
  INDEX `FK8ap0qqovdw3pwgsyuphb3gang` (`quizzesid` ASC) VISIBLE,
  INDEX `FKc31xkn83q9v6yf9gh2spkvxrc` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK8ap0qqovdw3pwgsyuphb3gang`
    FOREIGN KEY (`quizzesid`)
    REFERENCES `oboe`.`quizzes` (`quizzesid`),
  CONSTRAINT `FKc31xkn83q9v6yf9gh2spkvxrc`
    FOREIGN KEY (`user_id`)
    REFERENCES `oboe`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`reading`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`reading` (
  `readingid` BINARY(16) NOT NULL,
  `owner_id` BINARY(16) NOT NULL,
  `owner_type` VARCHAR(255) NOT NULL,
  `reading_text` VARCHAR(255) NOT NULL,
  `reading_type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`readingid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`reports` (
  `reportid` BINARY(16) NOT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `report_at` DATE NULL DEFAULT NULL,
  `status` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` BINARY(16) NULL DEFAULT NULL,
  PRIMARY KEY (`reportid`),
  INDEX `FK2o32rer9hfweeylg7x8ut8rj2` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK2o32rer9hfweeylg7x8ut8rj2`
    FOREIGN KEY (`user_id`)
    REFERENCES `oboe`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oboe`.`user_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oboe`.`user_answers` (
  `user_answers_id` BINARY(16) NOT NULL,
  `answer` VARCHAR(255) NULL DEFAULT NULL,
  `is_correct` BIT(1) NOT NULL,
  `questionid` BINARY(16) NULL DEFAULT NULL,
  `quizzesid` BINARY(16) NULL DEFAULT NULL,
  `user_id` BINARY(16) NULL DEFAULT NULL,
  PRIMARY KEY (`user_answers_id`),
  INDEX `FKfcuyfytivu3rshx477asge1r1` (`questionid` ASC) VISIBLE,
  INDEX `FKi2f2ogorxjctw94hn1xv29it6` (`quizzesid` ASC) VISIBLE,
  INDEX `FKk4u357ronsopa0vqf16deuxbt` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKfcuyfytivu3rshx477asge1r1`
    FOREIGN KEY (`questionid`)
    REFERENCES `oboe`.`questions` (`questionid`),
  CONSTRAINT `FKi2f2ogorxjctw94hn1xv29it6`
    FOREIGN KEY (`quizzesid`)
    REFERENCES `oboe`.`quizzes` (`quizzesid`),
  CONSTRAINT `FKk4u357ronsopa0vqf16deuxbt`
    FOREIGN KEY (`user_id`)
    REFERENCES `oboe`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
